### ISSUE TITLE
Facebook Chat Heads not working on Android 7.0+

### ISSUE THREAD

**Issue by kargoolek** [kevalpatel2106/android-samples#1]
`                                                                       --------- beginning of crash
07-19 16:27:44.122 10530-10530/com.example.chatheads E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.example.chatheads, PID: 10530
                                                                       java.lang.RuntimeException: Unable to create service com.example.chatheads.ChatHeadService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@bfea592 -- permission denied for window type 2002
                                                                           at android.app.ActivityThread.handleCreateService(ActivityThread.java:3414)
                                                                           at android.app.ActivityThread.-wrap4(Unknown Source:0)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                        Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@bfea592 -- permission denied for window type 2002
                                                                           at android.view.ViewRootImpl.setView(ViewRootImpl.java:788)
                                                                           at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                                           at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                                           at com.example.chatheads.ChatHeadService.onCreate(ChatHeadService.java:48)
                                                                           at android.app.ActivityThread.handleCreateService(ActivityThread.java:3404)
                                                                           at android.app.ActivityThread.-wrap4(Unknown Source:0) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                           at android.os.Looper.loop(Looper.java:164) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6540) 
                                                                           at java.lang.reflect.Method.invoke(Native Method`

**Comment by kargoolek** [comment]
OK, working after changing:

`    compileSdkVersion 26
    buildToolsVersion "26.0.0"`

to:

`    compileSdkVersion 25
    buildToolsVersion "25.0.0"`

**Comment by kevalpatel2106** [comment]
@kargoolek This may be due to background service changes applied in android O. You cannot make service forground directly after issuing `startService()` command. Use `NotificationManager.startServiceInForeground()` to create foreground service. More on that [here](https://medium.com/@kevalpatel2106/how-to-handle-background-services-in-android-o-f96783e65268).

**Comment by yfujiki** [comment]
Hello @kevalpatel2106. Thanks for great repo and a write up in Medium.

I just stumbled on the same issue and figured out that the true cause was very simple. 

`WindowManager.LayoutParams.TYPE_PHONE` is deprecated in SDKVersion 26 and up, that's why it's crashing for Oreo and up, and that's why lowering SDK build version works as well.

So, changing the LayoutParams initialization to this made it work for all environments.

```
        final WindowManager.LayoutParams params;

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            //Add the view to the window.
            params = new WindowManager.LayoutParams(
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,
                    WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
                    PixelFormat.TRANSLUCENT);
        } else {
            //Add the view to the window.
            params = new WindowManager.LayoutParams(
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.TYPE_PHONE,
                    WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
                    PixelFormat.TRANSLUCENT);
        }
```

Hope this helps somebody else!
