### ISSUE TITLE
Why does the app randomly crash?

### ISSUE THREAD

**Issue by WooyoungKang** [kevalpatel2106/android-samples#8]

**Comment by WooyoungKang** [comment]
This is the logcat

2019-01-29 13:38:03.003 6020-6020/com.example.chatheads E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.chatheads, PID: 6020
    java.lang.RuntimeException: Unable to create service com.example.chatheads.ChatHeadService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@bac7f01 -- permission denied for window type 2002
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3554)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@bac7f01 -- permission denied for window type 2002
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:982)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
        at com.example.chatheads.ChatHeadService.onCreate(ChatHeadService.java:48)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Ideasandkanishk** [comment]
It is crashing above version 26.
You have to just implement this
if (Build.VERSION.SDK_INT >= 26) {
        params= new WindowManager.LayoutParams(
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,
                    WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
                    PixelFormat.TRANSLUCENT
            );
    }
and for below it will work same.

Happy coding.

**Comment by mksantoki** [comment]
@Ideasandkanishk Yes working perfect. Thank you :)
